<?php
enum Violation: string
{
  case ILLEGAL_PARKING = "ILLEGAL PARKING";
  case RECKLESS_DRIVING = "RECKLESS DRIVING";
  case DISOBEYING_TRAFFIC_SIGNS = "DISOBEYING TRAFFIC SIGNS";
  case OVERSPEEDING = "OVERSPEEDING";
  case DRIVING_UNDER_INFLUENCE = "DRIVING UNDER INFLUENCE";
  case OBSTRUCTION = "OBSTRUCTION";
  case NO_DRIVER_LICENSE = "NO DRIVER LICENSE";
  case EXPIRED_LICENSE = "EXPIRED DRIVER LICENSE";
  case UNREGISTERED_VEHICLE = "UNREGISTERED VEHICLE";
  case NO_OR_CR = "NO OR/CR";
  case NUMBER_CODING = "NUMBER CODING";
  case NO_HELMET = "NO HELMET";
  case NO_SEATBELT = "NO SEATBELT";
}
?>